export { clientHintsFromHeaders } from "./client-hint-headers.js";
export { InputLimitError, RuleValidationError } from "./errors.js";
export {
  isAiClient,
  isBot,
  isChromeFamily,
  isCli,
  isConsole,
  isCrawler,
  isDesktop,
  isEmailClient,
  isEmbedded,
  isLibrary,
  isMediaPlayer,
  isMobile,
  isTablet,
  isTv,
  isWearable,
  isXr,
} from "./guards.js";
export { DEFAULT_MAX_USER_AGENT_LENGTH } from "./limits.js";
export { createParser, parse } from "./parser.js";
export type {
  BrowserInfo,
  BrowserRuleResult,
  ClientHintBrand,
  ClientHints,
  ClientInfo,
  ClientRuleResult,
  ClientType,
  CpuInfo,
  CpuRuleResult,
  DetectionRule,
  DeviceInfo,
  DeviceRuleResult,
  DeviceType,
  EngineInfo,
  EngineRuleResult,
  InputOverflowBehavior,
  OperatingSystemInfo,
  OperatingSystemRuleResult,
  ParseOptions,
  ParseResult,
  Parser,
  ParserOptions,
  RuleMatch,
  RulePack,
  RuleResult,
} from "./types.js";
